/* Generated by           cobc 2.2.0 */
/* Generated from         examples/hello_world.cbl */
/* Generated at           Jul 09 2023 02:41:47 */
/* GnuCOBOL build date    Jul 17 2018 20:29:40 */
/* GnuCOBOL package date  Sep 06 2017 18:48:43 UTC */
/* Compile command        cobc -C -o examples/hello_world.c examples/hello_world.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};


/* Constants */
static const cob_field c_1	= {13, (cob_u8_ptr)"Hello, World!", &a_1};

	/* Decimal constants */
